[package]
name = "nova-desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "nova_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[features]
default = []
admin = []

[dependencies]
nova-crypto = { path = "../../core/nova-crypto" }
nova-engine = { path = "../../core/nova-engine" }
nova-protocol = { path = "../../core/nova-protocol" }
nova-storage = { path = "../../core/nova-storage" }
nova-transport = { path = "../../core/nova-transport" }
libp2p.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-fs = "2"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
